### ISSUE TITLE
Fix the resizing bug when first opening Quizzes

### ISSUE THREAD

**Issue by doombubbles** [rooseveltcs/Studiam#3]
Example: in the now included saveyTest.studiam file

Sometime with certain configurations of terms the elements will be defaulted to format at the wrong size.

**Comment by doombubbles** [comment]
Get assigned @fechan

**Comment by ghost** [comment]
problem was the space between the term input boxes was not accounted for when its container was resized. The container now grows by 10px more each time to account for this
